#!/bin/bash

IP=futuretech.membershipauto.com

# Sync the working directory ft project up to the MA AWS server
# development environment (not production)

if [ "`basename $PWD`" != ft ]; then
    echo "Must run from ft directory"
    exit 1
fi

echo "Cleaning out graphs ..."
rm -rf public/graphs/*.png

echo "Syncing ..."
rsync -az . rails@$IP:/home/rails/ft
ssh rails@$IP ft/script/awsdevpatch

dol='$'
cat << EOF1
Edit script to see instructions to copy databse.

Don't forget rake db:migrate

EOF1
true <<EOF2
To copy database:
Make sure db/dumpsome.sh has all the tables you want.
read pw
export pw
./dumpsome.sh > dumpAprXX.sql
scp dumpApr18.sql rails@membershipauto.com:ft/db
On aws:  mysql -u dlaw -p${dol}pw ft_development < db/dumpAprXX.sql

EOF2
